module.exports = {
  LOAD_ROOMS: "LOAD_ROOMS",
  UPDATE_ROOM: "UPDATE_ROOM",
  USER_JOINED: "USER_JOINED",
  USER_JUMPED: "USER_JUMPED",
  USER_LEFT: "USER_LEFT",
  SEND_OFFER: 'SEND_OFFER',
  RECEIVE_OFFER: 'RECEIVE_OFFER',
  SEND_ANSWER: 'SEND_ANSWER',
  RECEIVE_ANSWER: 'RECEIVE_ANSWER',
  CREATE_ROOM: 'CREATE_ROOM',
  ERROR: 'ERROR',
  OTHER_PARTICIPANTS: 'OTHER_PARTICIPANTS',
  USER_DISCONNECTED: 'USER_DISCONNECTED'
};
